version: '3'
services:
  broker:
    build: broker

  auldfellas:
    build: auldfellas
    environment:
      SERVER_HOST: broker
    depends_on:
      - broker

  dodgygeezers:
    build: dodgygeezers
    environment:
      SERVER_HOST: broker
    depends_on:
      - broker

  girlsallowed:
    build: girlsallowed
    environment:
      SERVER_HOST: broker
    depends_on:
      - broker

  client:
    build: client
    environment:
      SERVER_HOST: broker
    depends_on:
      - broker
      - auldfellas
      - dodgygeezers
      - girlsallowed